In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../data/friday.csv")

In [3]:
df.head()

,Src IP dec,Src Port,Dst IP dec,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,ICMP Code,ICMP Type,Total TCP Flow Time,Label,Attempted Category
0,3232238130,56108,3232238083,3268,6,59:50.3,112740690,32,16,6448,...,343,16105402.14,4.988048e+05,16399772,15375229,-1,-1,112740690,BENIGN,-1
1,3232238130,42144,3232238083,389,6,59:50.3,112740560,32,16,6448,...,285,16105427.43,4.987937e+05,16399782,15375263,-1,-1,112740560,BENIGN,-1
2,134610945,0,134219268,0,0,00:31.4,113757377,545,0,0,...,19,12210358.40,6.935824e+06,20757030,5504997,-1,-1,0,BENIGN,-1
3,3232238105,5353,3758096635,5353,17,00:42.9,91997219,388,0,37151,...,16,13197637.00,5.826905e+06,19776791,5817470,-1,-1,0,BENIGN,-1
4,3232238105,123,301796989,123,17,00:42.4,66966070,6,6,288,...,1968172,64974431.00,0.000000e+00,64974431,64974431,-1,-1,0,BENIGN,-1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547557 entries, 0 to 547556
Data columns (total 89 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Src IP dec                  547557 non-null  int64
 1   Src Port                    547557 non-null  int64
 2   Dst IP dec                  547557 non-null  int64
 3   Dst Port                    547557 non-null  int64
 4   Protocol                    547557 non-null  int64
 5   Timestamp                   547557 non-null  object
 6   Flow Duration               547557 non-null  int64
 7   Total Fwd Packet            547557 non-null  int64
 8   Total Bwd packets           547557 non-null  int64
 9   Total Length of Fwd Packet  547557 non-null  int64
 10  Total Length of Bwd Packet  547557 non-null  int64
 11  Fwd Packet Length Max       547557 non-null  int64
 12  Fwd Packet Length Min       547557 non-null  int64
 13  Fwd Packet Length Mean      547557 non-null  float64
 14  Fwd Packet Length Std       547557 non-null  float64
 15  Bwd Packet Length Max       547557 non-null  int64
 16  Bwd Packet Length Min       547557 non-null  int64
 17  Bwd Packet Length Mean      547557 non-null  float64
 18  Bwd Packet Length Std       547557 non-null  float64
 19  Flow Bytes/s                547557 non-null  float64
 20  Flow Packets/s              547557 non-null  float64
 21  Flow IAT Mean               547557 non-null  float64
 22  Flow IAT Std                547557 non-null  float64
 23  Flow IAT Max                547557 non-null  int64
 24  Flow IAT Min                547557 non-null  int64
 25  Fwd IAT Total               547557 non-null  int64
 26  Fwd IAT Mean                547557 non-null  float64
 27  Fwd IAT Std                 547557 non-null  float64
 28  Fwd IAT Max                 547557 non-null  int64
 29  Fwd IAT Min                 547557 non-null  int64
 30  Bwd IAT Total               547557 non-null  int64
 31  Bwd IAT Mean                547557 non-null  float64
 32  Bwd IAT Std                 547557 non-null  float64
 33  Bwd IAT Max                 547557 non-null  int64
 34  Bwd IAT Min                 547557 non-null  int64
 35  Fwd PSH Flags               547557 non-null  int64
 36  Bwd PSH Flags               547557 non-null  int64
 37  Fwd URG Flags               547557 non-null  int64
 38  Bwd URG Flags               547557 non-null  int64
 39  Fwd RST Flags               547557 non-null  int64
 40  Bwd RST Flags               547557 non-null  int64
 41  Fwd Header Length           547557 non-null  int64
 42  Bwd Header Length           547557 non-null  int64
 43  Fwd Packets/s               547557 non-null  float64
 44  Bwd Packets/s               547557 non-null  float64
 45  Packet Length Min           547557 non-null  int64
 46  Packet Length Max           547557 non-null  int64
 47  Packet Length Mean          547557 non-null  float64
 48  Packet Length Std           547557 non-null  float64
 49  Packet Length Variance      547557 non-null  float64
 50  FIN Flag Count              547557 non-null  int64
 51  SYN Flag Count              547557 non-null  int64
 52  RST Flag Count              547557 non-null  int64
 53  PSH Flag Count              547557 non-null  int64
 54  ACK Flag Count              547557 non-null  int64
 55  URG Flag Count              547557 non-null  int64
 56  CWR Flag Count              547557 non-null  int64
 57  ECE Flag Count              547557 non-null  int64
 58  Down/Up Ratio               547557 non-null  float64
 59  Average Packet Size         547557 non-null  float64
 60  Fwd Segment Size Avg        547557 non-null  float64
 61  Bwd Segment Size Avg        547557 non-null  float64
 62  Fwd Bytes/Bulk Avg          547557 non-null  int64
 63  Fwd Packet/Bulk Avg         547557 non-null  int64
 64  Fwd Bulk Rate Avg           547557 non-null  int64
 65  Bwd Bytes/Bulk Avg          547557 non-null  int64
 66  Bwd Packet/Bulk Avg         547557 non-null  int64
 67  Bwd Bulk Rate Avg           547557 non-null  int64
 68  Subflow Fwd Packets         547557 non-null  int64
 69  Subflow Fwd Bytes           547557 non-null  int64
 70  Subflow Bwd Packets         547557 non-null  int64
 71  Subflow Bwd Bytes           547557 non-null  int64
 72  FWD Init Win Bytes          547557 non-null  int64
 73  Bwd Init Win Bytes          547557 non-null  int64
 74  Fwd Act Data Pkts           547557 non-null  int64
 75  Fwd Seg Size Min            547557 non-null  int64
 76  Active Mean                 547557 non-null  float64
 77  Active Std                  547557 non-null  float64
 78  Active Max                  547557 non-null  int64
 79  Active Min                  547557 non-null  int64
 80  Idle Mean                   547557 non-null  float64
 81  Idle Std                    547557 non-null  float64
 82  Idle Max                    547557 non-null  int64
 83  Idle Min                    547557 non-null  int64
 84  ICMP Code                   547557 non-null  int64
 85  ICMP Type                   547557 non-null  int64
 86  Total TCP Flow Time         547557 non-null  int64
 87  Label                       547557 non-null  object
 88  Attempted Category          547557 non-null  int64
dtypes: float64(25), int64(62), object(2)
memory usage: 371.8+ MB

In [5]:
df['ICMP Type'].value_counts()

ICMP Type
-1    547382
 3       143
 8        31
 0         1
Name: count, dtype: int64

In [6]:
df['ICMP Code'].value_counts()

ICMP Code
-1     547382
 1        114
 0         32
 3         25
 10         4
Name: count, dtype: int64

In [7]:
df[df["ICMP Type"] != -1]["Label"].value_counts()

Label
BENIGN      151
Portscan     24
Name: count, dtype: int64

In [8]:
df[df["ICMP Code"] != -1]["Label"].value_counts()

Label
BENIGN      151
Portscan     24
Name: count, dtype: int64

In [9]:
df.columns[df.nunique() <= 2].tolist()

['Fwd URG Flags',
 'Bwd URG Flags',
 'URG Flag Count',
 'Subflow Fwd Packets',
 'Subflow Bwd Packets',
 'Attempted Category']

In [10]:
df['Subflow Fwd Packets'].value_counts()

Subflow Fwd Packets
0    544327
1      3230
Name: count, dtype: int64

In [11]:
df['Subflow Bwd Packets'].value_counts()

Subflow Bwd Packets
0    547556
1         1
Name: count, dtype: int64

In [12]:
df['Attempted Category'].value_counts()

Attempted Category
-1    543490
 1      4067
Name: count, dtype: int64

In [13]:
df['CWR Flag Count'].value_counts()

CWR Flag Count
0     547423
1        121
2          6
3          2
6          2
23         1
9          1
8          1
Name: count, dtype: int64

In [14]:
df['URG Flag Count'].value_counts()

URG Flag Count
0    547557
Name: count, dtype: int64

In [15]:
df['ECE Flag Count'].value_counts()

ECE Flag Count
0    547461
2        83
1        13
Name: count, dtype: int64

In [16]:
len(df[(df['Subflow Fwd Packets'] == 0) & (df['Subflow Fwd Bytes'] > 0)])

370357

In [17]:
df[['Total Fwd Packet', 'Subflow Fwd Packets']].head(10)

   Total Fwd Packet  Subflow Fwd Packets
0                32                    0
1                32                    0
2               545                    1
3               388                    1
4                 6                    0
5                 6                    0
6               124                    0
7                10                    0
8                 4                    0
9               206                    0

In [18]:
df[["Fwd Segment Size Avg", "Bwd Segment Size Avg", "Fwd Packet Length Mean", "Bwd Packet Length Mean"]].head(10)

,Fwd Segment Size Avg,Bwd Segment Size Avg,Fwd Packet Length Mean,Bwd Packet Length Mean
0,201.500000,72.000000,201.500000,72.000000
1,201.500000,316.000000,201.500000,316.000000
2,0.000000,0.000000,0.000000,0.000000
3,95.750000,0.000000,95.750000,0.000000
4,48.000000,48.000000,48.000000,48.000000
5,48.000000,48.000000,48.000000,48.000000
6,275.725806,401.200000,275.725806,401.200000
7,160.200000,589.666667,160.200000,589.666667
8,48.000000,48.000000,48.000000,48.000000
9,205.116505,289.252632,205.116505,289.252632

In [19]:
df[["Packet Length Variance", "Packet Length Std"]].head(10)

   Packet Length Variance  Packet Length Std
0            31450.099290         177.341758
1            30619.460990         174.984173
2                0.000000           0.000000
3             3112.001938          55.785320
4                0.000000           0.000000
5                0.000000           0.000000
6           251692.678900         501.689823
7           443664.134500         666.081177
8                0.000000           0.000000
9           175496.533900         418.923065

In [21]:
df = df.drop(["Src IP dec", "Src Port", "Dst IP dec", "Dst Port", "Timestamp", 
              "Attempted Category", "ICMP Code", "ICMP Type", "URG Flag Count", 
              "Fwd URG Flags", "Bwd URG Flags", "Subflow Bwd Packets",
              "Subflow Bwd Bytes", "CWR Flag Count", "ECE Flag Count", "Subflow Fwd Packets",
              "Subflow Fwd Bytes", "Fwd Segment Size Avg", "Bwd Segment Size Avg",
              "Packet Length Variance"], axis=1)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547557 entries, 0 to 547556
Data columns (total 69 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Protocol                    547557 non-null  int64
 1   Flow Duration               547557 non-null  int64
 2   Total Fwd Packet            547557 non-null  int64
 3   Total Bwd packets           547557 non-null  int64
 4   Total Length of Fwd Packet  547557 non-null  int64
 5   Total Length of Bwd Packet  547557 non-null  int64
 6   Fwd Packet Length Max       547557 non-null  int64
 7   Fwd Packet Length Min       547557 non-null  int64
 8   Fwd Packet Length Mean      547557 non-null  float64
 9   Fwd Packet Length Std       547557 non-null  float64
 10  Bwd Packet Length Max       547557 non-null  int64
 11  Bwd Packet Length Min       547557 non-null  int64
 12  Bwd Packet Length Mean      547557 non-null  float64
 13  Bwd Packet Length Std       547557 non-null  float64
 14  Flow Bytes/s                547557 non-null  float64
 15  Flow Packets/s              547557 non-null  float64
 16  Flow IAT Mean               547557 non-null  float64
 17  Flow IAT Std                547557 non-null  float64
 18  Flow IAT Max                547557 non-null  int64
 19  Flow IAT Min                547557 non-null  int64
 20  Fwd IAT Total               547557 non-null  int64
 21  Fwd IAT Mean                547557 non-null  float64
 22  Fwd IAT Std                 547557 non-null  float64
 23  Fwd IAT Max                 547557 non-null  int64
 24  Fwd IAT Min                 547557 non-null  int64
 25  Bwd IAT Total               547557 non-null  int64
 26  Bwd IAT Mean                547557 non-null  float64
 27  Bwd IAT Std                 547557 non-null  float64
 28  Bwd IAT Max                 547557 non-null  int64
 29  Bwd IAT Min                 547557 non-null  int64
 30  Fwd PSH Flags               547557 non-null  int64
 31  Bwd PSH Flags               547557 non-null  int64
 32  Fwd RST Flags               547557 non-null  int64
 33  Bwd RST Flags               547557 non-null  int64
 34  Fwd Header Length           547557 non-null  int64
 35  Bwd Header Length           547557 non-null  int64
 36  Fwd Packets/s               547557 non-null  float64
 37  Bwd Packets/s               547557 non-null  float64
 38  Packet Length Min           547557 non-null  int64
 39  Packet Length Max           547557 non-null  int64
 40  Packet Length Mean          547557 non-null  float64
 41  Packet Length Std           547557 non-null  float64
 42  FIN Flag Count              547557 non-null  int64
 43  SYN Flag Count              547557 non-null  int64
 44  RST Flag Count              547557 non-null  int64
 45  PSH Flag Count              547557 non-null  int64
 46  ACK Flag Count              547557 non-null  int64
 47  Down/Up Ratio               547557 non-null  float64
 48  Average Packet Size         547557 non-null  float64
 49  Fwd Bytes/Bulk Avg          547557 non-null  int64
 50  Fwd Packet/Bulk Avg         547557 non-null  int64
 51  Fwd Bulk Rate Avg           547557 non-null  int64
 52  Bwd Bytes/Bulk Avg          547557 non-null  int64
 53  Bwd Packet/Bulk Avg         547557 non-null  int64
 54  Bwd Bulk Rate Avg           547557 non-null  int64
 55  FWD Init Win Bytes          547557 non-null  int64
 56  Bwd Init Win Bytes          547557 non-null  int64
 57  Fwd Act Data Pkts           547557 non-null  int64
 58  Fwd Seg Size Min            547557 non-null  int64
 59  Active Mean                 547557 non-null  float64
 60  Active Std                  547557 non-null  float64
 61  Active Max                  547557 non-null  int64
 62  Active Min                  547557 non-null  int64
 63  Idle Mean                   547557 non-null  float64
 64  Idle Std                    547557 non-null  float64
 65  Idle Max                    547557 non-null  int64
 66  Idle Min                    547557 non-null  int64
 67  Total TCP Flow Time         547557 non-null  int64
 68  Label                       547557 non-null  object
dtypes: float64(22), int64(46), object(1)
memory usage: 288.2+ MB

In [23]:
df.columns

Index(['Protocol', 'Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd RST Flags', 'Bwd RST Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'FIN Flag Count', 'SYN Flag Count',
       'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Fwd Bytes/Bulk Avg', 'Fwd Packet/Bulk Avg',
       'Fwd Bulk Rate Avg', 'Bwd Bytes/Bulk Avg', 'Bwd Packet/Bulk Avg',
       'Bwd Bulk Rate Avg', 'FWD Init Win Bytes', 'Bwd Init Win Bytes',
       'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'Total TCP Flow Time', 'Label'],
      dtype='object')

In [24]:
df[["Flow Duration", "Total TCP Flow Time"]].head(10)

   Flow Duration  Total TCP Flow Time
0      112740690            112740690
1      112740560            112740560
2      113757377                    0
3       91997219                    0
4       66966070                    0
5       66137889                    0
6      106176490            106176490
7       79593267             79593267
8       64318195                    0
9      116933759            116933759

In [25]:
counts = df.nunique()
counts[counts == 1]

Series([], dtype: int64)

In [26]:
df.to_csv("../data/friday_cleaned.csv", index=False)